# Importing the libraries required for web scraping

In [4]:
import re
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings("ignore")

brand=[]
colors=[]
batteries=[]
Price=[]
original_price=[]
rating=[]
Total_reviews=[]
Discount=[]

for i in range(1,12):
    url=f'https://www.flipkart.com/search?q=headphones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&p%5B%5D=facets.headphone_design%255B%255D%3DEarbud&p%5B%5D=facets.rating%255B%255D%3D4%25E2%2598%2585%2B%2526%2Babove&p%5B%5D=facets.headphone_type%255B%255D%3DTrue%2BWireless&page={i}'
    request_header = {'Content-Type': 'text/html; charset=UTF-8','User-Agent': 'Chrome/101.0.0.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0','Accept-Encoding': 'gzip, deflate, br'}   
    page = requests.get(url,headers=request_header)
    soup= BeautifulSoup(page.text)
    section= soup.find_all('div',class_= 'slAVV4')
    for i in section:
        t= i.find('a',class_='wjcEIp')
        text= t.text
        #print(text)
        #brands
        brands= re.findall('^\w+',text)
        if brands:
            brand.append(brands[0])
        else:
            brand.append(np.nan)
        #colors
        color=i.find('div',class_= 'NqpwHC')
        if color:
            colors.append(color.text)
        else:
            colors.append(np.nan)
        #batteries
        battery = re.findall('(\d+.( Hrs|Hours|HRS|hrs|hours|H|h))',text)
        if battery:
            batteries.append(battery[0])
        else:
            batteries.append(np.nan)
        ## rating
        rate= i.find('div',class_= 'XQDdHH')
        if rate:
            rating.append(rate.text)
        else:
            rating.append(np.nan)
        #Total_reviews
        reviews= i.find('span',class_= 'Wphh3N')
        if reviews:
            Total_reviews.append(reviews.text)
        else:
            Total_reviews.append(np.nan)
        #Price
        price= i.find('div', class_= 'Nx9bqj')
        if price:
            Price.append(price.text)
        else:
            Price.append(np.nan)
        #original_price
        Or_price= i.find('div', class_= 'yRaY8j')
        if Or_price:
            original_price.append(Or_price.text)
        else:
            original_price.append(np.nan)
        #Discount
        discount=i.find('div', class_= 'UkUFwK')
        if discount:
            Discount.append(discount.text)
        else:
            Discount.append(np.nan)

data={'Brands':brand,
      'Colors':colors,
      'Battery':batteries,
      'Price':Price,
      'Original_price':original_price,
      'Rating':rating,
      'Total_reviews':Total_reviews,
      'Discount':Discount
}

df=pd.DataFrame(data)
df

,Brands,Colors,Battery,Price,Original_price,Rating,Total_reviews,Discount
0,Aroma,"Electric White, True Wireless","(50H, H)",₹479,"₹2,999",3.9,(591),84% off
1,Noise,"Midnight Blue, True Wireless","(50 H, H)",₹899,"₹2,999",4,"(5,99,343)",70% off
2,boAt,"Mocha Elegance, True Wireless","(100 HRS, HRS)",₹899,"₹4,990",4,"(43,235)",81% off
3,boAt,"Pebble Black, True Wireless","(40 HRS, HRS)",₹799,"₹2,490",4,"(12,58,722)",67% off
4,realme,"Jazz Blue, True Wireless","(38 h, h)","₹1,199","₹2,999",4.2,"(3,66,317)",60% off
...,...,...,...,...,...,...,...,...
435,DIGIBUDS,"Black, True Wireless",NaN,₹600,"₹5,999",4.1,(11),89% off
436,Boult,"Glacier Blue, True Wireless","(35H, H)",₹799,"₹2,499",4.1,"(1,70,066)",68% off
437,Aroma,"Galaxy Green, True Wireless","(60H, H)",₹493,"₹2,899",3.9,(591),82% off
438,Sennheiser,"White Silver, True Wireless",NaN,"₹18,990","₹29,990",4,(58),36% off
439,TRIGGR,"Shadow Grey, True Wireless",NaN,₹999,"₹3,999",4,"(58,593)",75% off

In [2]:
df.head()

,Brands,Colors,Battery,Price,Original_price,Rating,Total_reviews,Discount
0,TRIGGR,"Army Green, True Wireless",NaN,₹799,"₹3,999",4,"(10,373)",80% off
1,Boult,"Electric Black, True Wireless","(48H, H)","₹1,099","₹2,999",4.1,"(1,32,105)",63% off
2,boAt,"Mocha Elegance, True Wireless","(100 HRS, HRS)",₹899,"₹4,990",4,"(43,235)",81% off
3,boAt,"Pebble Black, True Wireless","(40 HRS, HRS)",₹799,"₹2,490",4,"(12,58,722)",67% off
4,realme,"Jazz Blue, True Wireless","(38 h, h)","₹1,199","₹2,999",4.2,"(3,66,317)",60% off

# Exporting the exteacted data to a csv file

In [3]:
df.to_csv('WirelessHeadphones.csv')